#' Process And Make Tobii iChart
#'
#' @description \code{make_iChart()} is a wrapper function for the sequence of functions that
#'   take raw Tobii eyetracking data and converts it to a wide format
#'   that plays nicely with the Language Learning Lab's RScripts.
#' @param df_et A data frame of Tobii eye tracking data in long format. Typically generated by \code{read_tobii()} function.
#' @param df_metadata A data frame of PEEK metadata. Typically generated by \code{read_order()} function.
#' @param df_prescreen A data frame of PEEK prescreening information Typically generated by \code{read_vcx()} function.
#' @param df_timing A data frame of PEEK noun onset timing information. Typically generated by \code{read_timing_file()} function.
#' @param aois_list A data frame of AOI information. Typically generated by \code{read_aois()} function.
#' @param make_wide A boolean indicating whether you want to return a wide or long formatted iChart.
#' @param make_iChart_names A boolean indicating whether you want to return column names specifically
#'   formatted for the functions in iChartAnalyzeR package.
#' @export
#' @examples
#'   \dontrun{d <- make_iChart(df_et, df_metadata, df_prescreen, df_timing,
#'   aois_list, make_wide = TRUE, make_iChart_names = TRUE)}

make_iChart <- function(df_et, df_metadata, df_prescreen, df_timing, aois_list,
                        make_wide = TRUE,
                        make_iChart_names = TRUE) {

  if(make_wide == F & make_iChart_names == T ) stop('iChart needs to be in wide format to make iChart names. Did you mean to set make_wide = TRUE')

  d <- df_et %>%
    dplyr::left_join(df_metadata, by = c("trial_number")) %>%
    dplyr::left_join(df_prescreen, by = c("ParticipantName", "trial_number"))

  d <- d %>%
    dplyr::filter(.data$used == "yes") %>%
    add_time_crit_onset(df_timing = df_timing, onset_type = "noun") %>%
    add_time_bins() %>%
    code_aoi_looking(aois_list = aois_list) %>%
    code_target_looking() %>%
    identify_responses()

  if(make_wide & make_iChart_names) {
    d <- d %>%
      convert_to_wide() %>%
      make_iChart_names()
  } else if (make_wide) {
    d <- d %>% convert_to_wide()
  }
  d
}
