#' Read And Parse All .vcx Files In Directory
#'
#' This function allows you to read and parse all of the raw vcx files generated by iCoder.
#' @description \code{read_all_vcx()} reads parses a directory of .vcx coding files to
#'   to get prescreening information. The
#' @param dir_path A path to a directory of .vcx files.
#' @export
#' @examples
#'   d <- read_all_vcx(dir_path = "experiment_name/data/vcx_files/")

read_all_vcx <- function(dir_path) {
  files <- dir(path = dir_path,
               pattern = "*.vcx",
               full.names = T)
  files %>% purrr::map_df(read_vcx)
}
