#' Read And Parse Tobii File
#'
#' This function allows you to read and parse a single raw tsv file generated by Tobii
#' @description \code{read_tobii()} is a special case of \code{read_tsv()}. It's useful for doing minor data
#'    processing on the raw tsv file that is unique to the Language Learning Lab.
#'    If you set \code{tidy = FALSE}, the function behaves like the default \code{read_tsv()}. Note that
#'    you are able to pass along any arguments that you would use with \code{read_tsv()}.
#' @param file Either a path to a file, a connection, or literal data.
#' @param tidy A boolean, if tidy = FALSE this functions behaves just \code{read_tsv()}.
#' @param ... Additional arguments, typically used to control the \code{read_tsv() function}.
#' @export
#' @examples
#' \dontrun{d <- read_tobii(file = "187_Habla2_25_Clips.tsv", tidy = TRUE)}

read_tobii <- function(file, tidy = FALSE, ...) {
  d <- readr::read_tsv(file = file,  col_types = cols(), ...)
  if (tidy) {
    d %>%
      clean_tobii_variables() %>%
      make_tobii_trials() %>%
      add_trial_timstamps()
  } else {
    d
  }
}

process_trial_timestamps <- function(trial_df) {
  trial_df %>%
    dplyr::arrange(RecordingTimestamp) %>%
    dplyr::mutate(prev_time_stamp = dplyr::lag(RecordingTimestamp, default = min(RecordingTimestamp)),
                  time_diff = RecordingTimestamp - prev_time_stamp,
                  timestamp_trial = cumsum(time_diff)) %>%
    dplyr::select(-prev_time_stamp, -time_diff)
}

add_trial_timstamps <- function(df) {
  df %>%
    split(.$MediaName, .$ParticipantName) %>%
    purrr::map_dfr(process_trial_timestamps)
}

clean_tobii_variables <- function(df) {
  df %>%
    dplyr::select(.data$ParticipantName,
                  .data$StudioEvent,
                  .data$MediaName,
                  .data$RecordingTimestamp,
                  tidyselect::contains("GazePoint")) %>%
    dplyr::rename(gaze_x = `GazePointX..ADCSpx.`,
                  gaze_y = `GazePointY..ADCSpx.`)
}

make_tobii_trials <- function(df) {
  df %>%
    dplyr::filter(!is.na(.data$MediaName)) %>%
    dplyr::mutate(MediaName = clean_trial_name(MediaName),
                  trial_number = as.integer(stringr::str_extract(MediaName, "[[:digit:]]+")))
}

clean_trial_name <- function(trial_name) {
  trial_name <- stringr::str_replace(trial_name, ".avi", "")
  trial_name <- stringr::str_replace(trial_name, " ", "_")
  trial_name <- stringr::str_to_lower(trial_name)
  trial_name
}
